### ISSUE TITLE
images

### ISSUE THREAD

**Issue by Beshario** [Beshario/RoboNDProj2#1]
![dh parameter reference frame](https://user-images.githubusercontent.com/6395647/30779703-9bb8ff02-a0c5-11e7-8cc0-52bacc8e6bea.jpeg)

![urdf file reference frame](https://user-images.githubusercontent.com/6395647/30779704-9bbaa190-a0c5-11e7-9108-4388e473f6ad.png)

![ik](https://user-images.githubusercontent.com/6395647/30779765-8266aa7a-a0c7-11e7-871c-4d21910fac6f.png)

**Comment by TehseenHasan** [comment]
How you made these images? Which software is used?

**Comment by Beshario** [comment]
I used Illustrator for this part to explain the inverse-kinematics of this project robot.
